
import java.util.Timer;
import java.util.TimerTask;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Turma A
 */
public class SmartTermo extends javax.swing.JFrame {
    
    private double temperature;
    private float humidity;

    /**
     * Creates new form SmartTermo
     */
    public SmartTermo() {
        initComponents();
        simulateCurrentTemp();
        this.temperature = 25;
        this.humidity = 60;
        jLabelCurrentTemp.setText(temperature + "º");
        jLabelCurrentH.setText(humidity + "%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCT = new javax.swing.JLabel();
        jLabelDT = new javax.swing.JLabel();
        jButtonMoreT = new javax.swing.JButton();
        jButtonLessT = new javax.swing.JButton();
        jLabelH = new javax.swing.JLabel();
        jLabelDH = new javax.swing.JLabel();
        jButtonMoreH = new javax.swing.JButton();
        jButtonLessH = new javax.swing.JButton();
        jLabelCurrentTemp = new javax.swing.JLabel();
        jLabelDesiredTemp = new javax.swing.JLabel();
        jLabelCurrentH = new javax.swing.JLabel();
        jLabelDesiredH = new javax.swing.JLabel();
        jButtonCelsius = new javax.swing.JButton();
        jButtonFahrenheit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCT.setText("Current Temp:");

        jLabelDT.setText("Desired Temp:");

        jButtonMoreT.setText("+");
        jButtonMoreT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoreTActionPerformed(evt);
            }
        });

        jButtonLessT.setText("-");
        jButtonLessT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLessTActionPerformed(evt);
            }
        });

        jLabelH.setText("H:");

        jLabelDH.setText("DH:");

        jButtonMoreH.setText("+");
        jButtonMoreH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoreHActionPerformed(evt);
            }
        });

        jButtonLessH.setText("-");
        jButtonLessH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLessHActionPerformed(evt);
            }
        });

        jLabelCurrentTemp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCurrentTemp.setText("25º");

        jLabelDesiredTemp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDesiredTemp.setText("27º");

        jLabelCurrentH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCurrentH.setText("60%");

        jLabelDesiredH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDesiredH.setText("50%");

        jButtonCelsius.setText("Cº");
        jButtonCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCelsiusActionPerformed(evt);
            }
        });

        jButtonFahrenheit.setText("Fº");
        jButtonFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFahrenheitActionPerformed(evt);
            }
        });

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDT)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDesiredTemp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButtonLessT)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelDH)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelDesiredH))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelH)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelCurrentH))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonMoreT)
                                .addGap(205, 205, 205)
                                .addComponent(jButtonLessH)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonMoreH))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCelsius)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonFahrenheit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCT)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCurrentTemp)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCT, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCurrentTemp)
                    .addComponent(jLabelH)
                    .addComponent(jLabelCurrentH))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDT)
                    .addComponent(jLabelDesiredTemp)
                    .addComponent(jLabelDH)
                    .addComponent(jLabelDesiredH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLessT)
                    .addComponent(jButtonMoreT)
                    .addComponent(jButtonLessH)
                    .addComponent(jButtonMoreH))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCelsius)
                    .addComponent(jButtonFahrenheit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String toString(float value){
        return ""+value;
    }
    private void jButtonLessTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLessTActionPerformed
        this.temperature -= 0.5;
        jLabelDesiredTemp.setText(temperature + "º");
        jTextAreaLog.append("Diminuiu a temperatura 0.5 graus");
    }//GEN-LAST:event_jButtonLessTActionPerformed

    private void jButtonMoreTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoreTActionPerformed
        this.temperature += 0.5;
        jLabelDesiredTemp.setText(temperature + "º");
        jTextAreaLog.append("Aumentou a temperatura 0.5 graus");
    }//GEN-LAST:event_jButtonMoreTActionPerformed

    private void jButtonLessHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLessHActionPerformed
        this.humidity -= 5;
        jLabelDesiredH.setText(humidity + "%");
    }//GEN-LAST:event_jButtonLessHActionPerformed

    private void jButtonMoreHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoreHActionPerformed
        this.humidity += 5;
        jLabelDesiredH.setText(humidity + "%");
    }//GEN-LAST:event_jButtonMoreHActionPerformed

    private void jButtonCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCelsiusActionPerformed
        jLabelCurrentTemp.setText(temperature + "ºC");
        jLabelDesiredTemp.setText(temperature + "ºC");
    }//GEN-LAST:event_jButtonCelsiusActionPerformed

    private void jButtonFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFahrenheitActionPerformed
        double fahrenheit = ((9*temperature)/5)+32; 
        jLabelCurrentTemp.setText(fahrenheit + "ºF");
        jLabelDesiredTemp.setText(fahrenheit + "ºF"); 
    }//GEN-LAST:event_jButtonFahrenheitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartTermo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCelsius;
    private javax.swing.JButton jButtonFahrenheit;
    private javax.swing.JButton jButtonLessH;
    private javax.swing.JButton jButtonLessT;
    private javax.swing.JButton jButtonMoreH;
    private javax.swing.JButton jButtonMoreT;
    private javax.swing.JLabel jLabelCT;
    private javax.swing.JLabel jLabelCurrentH;
    private javax.swing.JLabel jLabelCurrentTemp;
    private javax.swing.JLabel jLabelDH;
    private javax.swing.JLabel jLabelDT;
    private javax.swing.JLabel jLabelDesiredH;
    private javax.swing.JLabel jLabelDesiredTemp;
    private javax.swing.JLabel jLabelH;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaLog;
    // End of variables declaration//GEN-END:variables

    private void simulateCurrentTemp(){
        Timer timer = new Timer();
        TimerTask timerTask = new TimerTask() {
            @Override
            public void run() {
                temperature = (Math.random() * 30);
                jLabelCurrentTemp.setText(temperature + "º");
            }
        };
        
        timer.scheduleAtFixedRate(timerTask, 0, 1000);
    }
}
